name: example
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  app_core:
    path: ../

  # Restful
  retrofit: ^4.0.1
  json_annotation: ^4.0.1

  # Core libs
  get_it: ^7.6.0
  injectable: ^2.1.2

  get: ^4.1.4
  logger: ^1.0.0

  webview_flutter: ^4.2.1

  keyboard_service: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true